### PR TITLE
Fix couple bugs, update graphics display to not flicker

### PR DESCRIPTION
**Pull request by Sothatsit**
Hello, I read through the code and found a couple of bugs, so have made some changes to fix those.

I've also updated the graphics display to use anti-aliasing and double buffering so that it doesn't flicker and (imo) looks nicer:
Screen Shot 2020-09-22 at 5 42 14 Integration

Hope this is helpful 🙂
~Paddy Lamont

### CODE REVIEW

**Review by drtnf — APPROVED** [review]
Thanks Paddy. They’re sensible changes.

**Comment by drtnf** [comment]
Had a weird issue with the improved graphics approach where the canvas wouldn’t render. However, when I set the frame to be resizable on line 138, it rendered fine. Any ideas, or is anyone else experiencing that?

**Comment by Sothatsit** [comment]
> Had a weird issue with the improved graphics approach where the canvas wouldn’t render. However, when I set the frame to be resizable on line 138, it rendered fine. Any ideas, or is anyone else experiencing that?

I've not been able to reproduce this unfortunately. Could try calling `revalidate();` after `pack();` if maybe its a validation issue, but otherwise if just removing that line fixes it then that'd be better than it remaining broken.

**Comment by drtnf** [comment]
I'm running ubuntu 20. It look's like your code may be ignoring system level repainting, which may be the root of the issue. It might be safer to replace the repaintCanvas() method with the traditional paint(Graphics g)? That seems to work for me. Any thoughts?

**Comment by drtnf** [comment]
I'll just use the setResizable(true) hack for now, until someone reproduces the error.

**Comment by Sothatsit** [comment]
Ah that might explain it. Could try calling repaintCanvas from the overridden paint method? The reason I had used the different method was so that we could use the buffer strategy to paint in order to stop the flickering I had on my Mac. My brother has a Linux machine so when I'm home I can see if I can reproduce it on his machine 👍

**Comment by drtnf** [comment]
That seems to fix it. (calling repaintCanvas from the frame's paint method). I'll push that change in case anyone else has the issue.

**Pull request merged**
