### PR TITLE
Add control of the manual agent through the display

### PR DESCRIPTION
**Pull request by Sothatsit**
Hey Tim, I was really hungover so decided to add this to three chess instead of studying. Not very useful but thought interesting nonetheless. It basically just lets you click the pieces and click where you want to move them for the manual agent.

I also added the outlines on the darker squares cause I found it hard to see the green pieces when they were on the dark blue.

Can still use the console scanner input after these changes just have to pass false along with the agent's name to the constructor of ManualAgent. Like `new ManualAgent("A", false)`.
manual_mode

### CODE REVIEW

**Review by drtnf — CHANGES_REQUESTED** [review]
Hi Paddy, That's impressive. I'm a little wary of approving the PR as it's quite big, and I'm not entirely happy with the architectural decisions. I don't think board should have any references to display. As an entity class it should be independent of any of the interface  classes. You could perhaps push to a different branch, or we could talk about refactoring the code a bit.

**Comment by Sothatsit** [comment]
> Hi Paddy, That's impressive. I'm a little wary of approving the PR as it's quite big, and I'm not entirely happy with the architectural decisions. I don't think board should have any references to display. As an entity class it should be independent of any of the interface classes. You could perhaps push to a different branch, or we could talk about refactoring the code a bit.

That makes a lot of sense removing it from Board, especially with the recent Serializable changes. Could instead pass the display directly to the agent by adding set/get methods to the Agent base class? Would be similar to the current setBoard method of Agent then.

**Comment by drtnf** [comment]
I'd suggest just building a GUIAgent class with a reference to the display. That would minimize the dependencies between the GUI and the logic.

**Review by drtnf — CHANGES_REQUESTED** [review]
That’s looking a lot better. Why don’t we have the display as a static variable in the GUIAgent class, and then we can get rid of all that ugly instance of stuff in the play method.

**Review by drtnf — COMMENTED** [review]
Also, do you know why the GUIAgent was included in the commit? Iwas hoping the repo would ignore all new code added in the agents package.

**Comment by Sothatsit** [comment]
> That’s looking a lot better. Why don’t we have the display as a static variable in the GUIAgent class, and then we can get rid of all that ugly instance of stuff in the play method.

Let me change that up real quick 👍 

> Also, do you know why the GUIAgent was included in the commit? Iwas hoping the repo would ignore all new code added in the agents package.

Oh yeah, this branch is a bit old so it doesn't actually include the commit on master with the `.gitignore` changes yet, so that's why it still got included.

**Pull request merged**
